name: Test replace_hosts_file on multiple macOS versions

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        macos-version: [macos-10.15, macos-11, macos-12, macos-13]  # Ajouter ici d'autres versions si elles deviennent disponibles
    runs-on: ${{ matrix.macos-version }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set executable permissions
      run: chmod +x ./replace_hosts_file

    - name: Run the executable
      run: sudo ./replace_hosts_file
